name: 自動更新電子股資料庫 JSON

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安裝依賴
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: 執行更新
      run: python generate_db.py

    - name: Commit & Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add electronic_stocks_db.json
        git commit -m "自動更新電子股 JSON $(date '+%Y-%m-%d')" || echo "無變更"
        git push || echo "Push 跳過"
