name: 自動更新電子股資料庫 JSON

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-db:
    runs-on: ubuntu-latest
    
    # --- 關鍵修正：必須加入這段權限設定 ---
    permissions:
      contents: write
    # ------------------------------------

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安裝依賴
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 tqdm

    - name: 執行更新
      run: python generate_db.py

    - name: Commit & Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add taiwan_electronic_stocks.json
        # 如果檔案沒變動，git commit 會失敗，所以加上 || echo 確保流程不中斷
        git commit -m "自動更新電子股 JSON $(date '+%Y-%m-%d')" || exit 0
        git push
