name: 自動更新台股電子股資料庫 JSON

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00（台灣時間早上 08:00）執行一次
  push:
    branches: [ main ]   # 每次 push main 分支也執行
  workflow_dispatch:     # 允許手動觸發

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取儲存庫
      uses: actions/checkout@v4

    - name: 設定 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安裝依賴套件
      run: |
        python -m pip install --upgrade pip
        pip install yfinance requests beautifulsoup4 pandas

    - name: 執行程式產生 JSON
      run: python stock.py   # 如果你的程式檔名不同，請改成正確名稱

    - name: Commit & Push 更新後的 JSON
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add electronic_stocks_db.json
        git commit -m "自動更新電子股資料庫 JSON [skip ci]" || echo "No changes to commit"
        git push
